/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 *
 * This file has been generated using rpcgen for use with XDR to serialise
 * the transaction token structs. Function definitions for sending and comparing
 * transaction tokens have been added by me
 */

#ifndef _B_MESSAGES_H_RPCGEN
#define _B_MESSAGES_H_RPCGEN

#include <rpc/rpc.h>
#include <string.h>
#include "utilities.h"

#ifdef __cplusplus
extern "C" {
#endif


struct trans_req {
	char *payer;
	u_int value;
};
typedef struct trans_req trans_req;

struct trans_tok {
	char *payer;
	u_int serial;
	u_int value;
	char *bank_sig;
	u_int sig_len;
};
typedef struct trans_tok trans_tok;

struct trans_req *create_trans_req(char *payer, u_int value);
struct trans_tok *create_trans_tok(char *payer, u_int serial, u_int value, char *sig);
int trans_tok_equals(struct trans_tok *t1, struct trans_tok *t2);
void print_trans_tok(struct trans_tok *t);
int get_trans_tok(BIO* bio, struct trans_tok *t);
int send_trans_tok(BIO *bio, struct trans_tok *t);
int send_create_trans_tok(BIO *bio, char* payer, u_int serial, u_int value, unsigned char *sig);
unsigned char* buffer_trans_tok(struct trans_tok *t, int * size);
int get_trans_tok_from_buf(char *buf, struct trans_tok *t);
char * send_trans_tok_to_buf(struct trans_tok *t);
int send_trans_req(BIO *bio, struct trans_req* r);
int send_create_trans_req(BIO *bio, char* payer, u_int value);
int get_trans_req(BIO* bio, struct trans_req *r);
void print_trans_req(struct trans_req *r);


/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_trans_req (XDR *, trans_req*);
extern  bool_t xdr_trans_tok (XDR *, trans_tok*);

#else /* K&R C */
extern bool_t xdr_trans_req ();
extern bool_t xdr_trans_tok ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_B_MESSAGES_H_RPCGEN */
