
#include <string.h>
/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 *
 * This file contains the definitions of the message_client messages. These messages
 * are sent between all applications and generally are sent early in the communication
 * to inform the server of the operation that needs performing.
 *
 * It also contains the definitions of the XDR serialisation functions
 *
 * Some of the functions in utilities.c should be in here. Specifically the message
 * sending/receiving functions.
 */

#ifndef _MESSAGES_H_RPCGEN
#define _MESSAGES_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


extern char *strdup(const char *str);
enum message_c_ctrl {
	LOGIN = 0,
	ADD = 1,
	UPDATE = 2,
	DELETE = 3,
	FETCH = 4,
	FETCH_FAIL = 5,
	LIST = 6,
	VERIFY = 7,
	LOGOUT = 8,
	REGISTER = 9,
	B_QUERY = 10,
	B_WITHDRAW = 11,
	B_VERIFY = 12,
};
typedef enum message_c_ctrl message_c_ctrl;

struct message_client {
	enum message_c_ctrl ctrl;
	char *name; //either a filename or username
	char *pword; //a password when logging in/register otherwise not used
	u_int file_perm; //the local file permissions of the file being sent
	long file_size; //the size of the file being sent
};
typedef struct message_client message_client;


struct message_client * message_create(enum message_c_ctrl ctrl, char* name, char* pword, int file_perm, long file_size);
void message_print_c(struct message_client* m);

int string_to_ctrl(char *s);
char *ctrl_to_string(enum message_c_ctrl c);

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_message_c_ctrl (XDR *, message_c_ctrl*);
extern  bool_t xdr_message_client (XDR *, message_client*);

#else /* K&R C */
extern bool_t xdr_message_c_ctrl ();
extern bool_t xdr_message_client ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_MESSAGES_H_RPCGEN */
